In [4]:
import numpy as np


class sample(object):
    def __init__(self, X, n_subspace):
        self.idx_subspace = self.random_subspace(X, n_subspace)

    def __call__(self, X, y):
        idx_obj = self.bootstrap_sample(X)
        X_sampled, y_sampled = self.get_subsample(
            X, y, self.idx_subspace, idx_obj)
        return X_sampled, y_sampled

    @staticmethod
    def bootstrap_sample(X, random_state=42):
        """
        Заполните тело этой функции таким образом, чтобы она возвращала массив индексов выбранных при помощи бэггинга индексов.
        Пользуйтесь только инструментами, реализованными в numpy.random, выставляя везде, где это необходимо, random_state=42
        """
        arr = np.random.choice(len(X), size=len(X), replace=True)

        uniq_idxes = np.unique(arr)
        return uniq_idxes

    @staticmethod
    def random_subspace(X, n_subspace, random_state=42):
        first_elem = X[0]
        idxes = np.random.choice(
            len(first_elem), size=n_subspace, replace=False)
        return idxes

    @staticmethod
    def get_subsample(X, y, idx_subspace, idx_obj):
        """
        Заполните тело этой функции таким образом, чтобы она возвращала подвыборку x_sampled, y_sampled
        по значениям индексов признаков(idx_subspace) и объектов(idx_obj) , которые должны в неё попасть
        """

        return X[np.ix_(idx_obj, idx_subspace)], y[idx_obj]

In [5]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([1, 2, 3])
s = sample(X, 2)

bootstrap_indices = s.bootstrap_sample(X)
X_sampled, y_sampled = s.get_subsample(X, Y, s.idx_subspace, bootstrap_indices)

In [6]:
# Строки, выбранные из исходного массива X
bootstrap_indices

array([1, 2])

In [7]:
# Столбцы, выбранные из исходного массива X
s.idx_subspace

array([0, 1])

In [8]:
# Матрица на выходе
X_sampled

array([[4, 5],
       [7, 8]])

In [9]:
# Вектор ответов на выходе
y_sampled

array([2, 3])